In [3]:
import numpy as np
import pandas as pd

In [4]:
x =[
  2.266724480927481e-13,
  1.2445615314885865e-13,
  0.002767328242402286,
  397.72759765274736,
  0.00010736425572054334,
  398.21633756128233,
  0.0001073642563400774,
  0,
  4.936512138984619e-13,
  398.26875045317917,
  0,
  3.3328864469594053,
  2.422963203653178e-15,
  0,
  9.999592164262636e-15,
  3.7241977853985574e-15,
  3.8024809944239394e-18,
  7.829389562724617e-16,
  3.3330286021917614,
  3.33302860218078,
  0.8894354584143245,
  3.419086377521119e-15,
  3.188606571472451e-15,
  0.8894354584305514,
  0.8894271641872681,
  1.47017143395775e-18,
  0,
  0,
  1.196326431340095e-16,
  0,
  6.104414678597803e-17,
  4.2778816080317935e-17,
  3.1418666092010174e-17,
  6.05521170478541e-17,
  3.361815978403873e-17,
  3.359198306840574e-17,
  3.252740862097541e-17,
  3.136217897711245e-17,
  3.384869794474141e-17,
  4.2805806409872094e-17,
  3.3950123163254524e-14,
  2.931667461626887e-14,
  3.2515232584339865e-14,
  2.989770552872522e-14,
  3.2424781867062826e-14,
  39.54922625962483,
  3.0662435590228224e-14,
  39.54530849800763,
  2.701248925077879e-14,
  3.1418133154472725e-14,
  17.550106870260354,
  1.1730980778489564e-17,
  4.401880962599321e-18,
  2.596232180337181e-18,
  5.8667108101265324e-18,
  17.551581931036292,
  8.99797219065376e-16,
  1.7265117056235566e-18,
  17.552481541555473,
  17.552575280747988,
  1.0718418398505518e-16,
  1.0648666653774778e-16,
  1.253801891840519e-16,
  1.0649735422797451e-16,
  1.0803232327778339e-16,
  1.1569315676052633e-16,
  1.2476142540544778e-16,
  1.0512573573131961e-16,
  1.0546368829907136e-16,
  1.25537731712106e-16,
  8.787106884591146e-17,
  8.43293028747216e-17,
  8.387424335949132e-17,
  8.816629648988093e-17,
  8.544490494000706e-17,
  8.374436080530895e-17,
  8.520901021426494e-17,
  8.329794573294723e-17,
  8.690231630173089e-17,
  8.749471971110758e-17,
  8.015046798064692e-17,
  8.458464883596221e-17,
  7.659992045722264e-17,
  8.464584011897921e-17,
  8.503852388486571e-17,
  7.957320506687334e-17,
  8.374276161003601e-17,
  8.317457576296113e-17,
  8.003592146544215e-17,
  8.064038946919654e-17,
  2.20059775158323e-17,
  2.1726704103802045e-17,
  2.1240259578001867e-17,
  2.1590881101562556e-17,
  2.132092020395055e-17,
  2.4039591073494216e-17,
  1.924359108010952e-17,
  2.1448446273039476e-17,
  2.2321815880808925e-17,
  2.073947462855139e-17,
  5.842415256519993e-16,
  5.545266265413024e-16,
  5.813470279748625e-16,
  5.796314919267103e-16,
  5.927573133436287e-16,
  5.861569218997485e-16,
  5.847617987997521e-16,
  6.111994065896087e-16,
  5.570263591464215e-16,
  5.916128834847876e-16,
  1.8887855180201455e-17,
  2.0233949736154758e-17,
  1.9171417640674825e-17,
  1.9819280067001042e-17,
  2.1312109946976832e-17,
  2.0178984089329455e-17,
  1.8037220896129648e-17,
  1.833256022669569e-17,
  1.8873789906792122e-17,
  1.7892185014983994e-17,
  6.769772948022651e-17,
  7.045541353777585e-17,
  7.555958970767534e-17,
  7.495037392647824e-17,
  6.861085330221087e-17,
  7.190122730908434e-17,
  7.16835787869762e-17,
  6.825266854352242e-17,
  7.253984821893087e-17,
  7.262807006166675e-17,
  2.6963920212922474e-17,
  2.6836517100004778e-17,
  2.883435602805397e-17,
  2.81953670703756e-17,
  2.6933019184902718e-17,
  2.972665326386079e-17,
  2.5850773291207708e-17,
  2.9112608503347654e-17,
  2.7982168082409583e-17,
  2.5686179738321953e-17,
  4.650747757856342e-17,
  4.1973584476553605e-17,
  4.2973578318991375e-17,
  4.159049698633357e-17,
  1.7752086607801916e-14,
  0.0025674131537900048,
  1.3222933439552776e-18,
  2.13415788215718e-17,
  16.99329476455959,
  16.993294764628775,
  0.001847150825104225,
  0,
  13.82642560118834,
  7.765333237038272e-16,
  13.826425601137927,
  3.700892602349696e-13,
  0,
  0.00006772689779726635,
  0.00006772689710496189,
  0.00006772689759786975
]

In [5]:
np.floor(x)

array([  0.,   0.,   0., 397.,   0., 398.,   0.,   0.,   0., 398.,   0.,
         3.,   0.,   0.,   0.,   0.,   0.,   0.,   3.,   3.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,  39.,   0.,  39.,   0.,   0.,  17.,   0.,   0.,   0.,   0.,
        17.,   0.,   0.,  17.,  17.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,  16.,  16.,   0.,   0.,  13.,   0.,
        13.,   0.,   0.,   0.,   0.,   0.])

In [6]:
from more_itertools import grouper

In [7]:
company_names = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]

group_list = [i for i in grouper(len(company_names), x)]
len(group_list)

16

In [8]:
schrotte_names = (f"F{i}" for i in range(1, 17))
group_list[1]

(0,
 3.3328864469594053,
 2.422963203653178e-15,
 0,
 9.999592164262636e-15,
 3.7241977853985574e-15,
 3.8024809944239394e-18,
 7.829389562724617e-16,
 3.3330286021917614,
 3.33302860218078)

In [9]:
schrotte_names

In [10]:
schrotte_names = [f"F{i}" for i in range(1, 17)]
einkaufsliste = {k:v for k in schrotte_names for v in group_list}

In [11]:
einkaufsliste = dict(zip(schrotte_names, group_list))

In [12]:
einkaufsliste

{'F1': (2.266724480927481e-13,
  1.2445615314885865e-13,
  0.002767328242402286,
  397.72759765274736,
  0.00010736425572054334,
  398.21633756128233,
  0.0001073642563400774,
  0,
  4.936512138984619e-13,
  398.26875045317917),
 'F2': (0,
  3.3328864469594053,
  2.422963203653178e-15,
  0,
  9.999592164262636e-15,
  3.7241977853985574e-15,
  3.8024809944239394e-18,
  7.829389562724617e-16,
  3.3330286021917614,
  3.33302860218078),
 'F3': (0.8894354584143245,
  3.419086377521119e-15,
  3.188606571472451e-15,
  0.8894354584305514,
  0.8894271641872681,
  1.47017143395775e-18,
  0,
  0,
  1.196326431340095e-16,
  0),
 'F4': (6.104414678597803e-17,
  4.2778816080317935e-17,
  3.1418666092010174e-17,
  6.05521170478541e-17,
  3.361815978403873e-17,
  3.359198306840574e-17,
  3.252740862097541e-17,
  3.136217897711245e-17,
  3.384869794474141e-17,
  4.2805806409872094e-17),
 'F5': (3.3950123163254524e-14,
  2.931667461626887e-14,
  3.2515232584339865e-14,
  2.989770552872522e-14,
  3.2424781867062826e-14,
  39.54922625962483,
  3.0662435590228224e-14,
  39.54530849800763,
  2.701248925077879e-14,
  3.1418133154472725e-14),
 'F6': (17.550106870260354,
  1.1730980778489564e-17,
  4.401880962599321e-18,
  2.596232180337181e-18,
  5.8667108101265324e-18,
  17.551581931036292,
  8.99797219065376e-16,
  1.7265117056235566e-18,
  17.552481541555473,
  17.552575280747988),
 'F7': (1.0718418398505518e-16,
  1.0648666653774778e-16,
  1.253801891840519e-16,
  1.0649735422797451e-16,
  1.0803232327778339e-16,
  1.1569315676052633e-16,
  1.2476142540544778e-16,
  1.0512573573131961e-16,
  1.0546368829907136e-16,
  1.25537731712106e-16),
 'F8': (8.787106884591146e-17,
  8.43293028747216e-17,
  8.387424335949132e-17,
  8.816629648988093e-17,
  8.544490494000706e-17,
  8.374436080530895e-17,
  8.520901021426494e-17,
  8.329794573294723e-17,
  8.690231630173089e-17,
  8.749471971110758e-17),
 'F9': (8.015046798064692e-17,
  8.458464883596221e-17,
  7.659992045722264e-17,
  8.464584011897921e-17,
  8.503852388486571e-17,
  7.957320506687334e-17,
  8.374276161003601e-17,
  8.317457576296113e-17,
  8.003592146544215e-17,
  8.064038946919654e-17),
 'F10': (2.20059775158323e-17,
  2.1726704103802045e-17,
  2.1240259578001867e-17,
  2.1590881101562556e-17,
  2.132092020395055e-17,
  2.4039591073494216e-17,
  1.924359108010952e-17,
  2.1448446273039476e-17,
  2.2321815880808925e-17,
  2.073947462855139e-17),
 'F11': (5.842415256519993e-16,
  5.545266265413024e-16,
  5.813470279748625e-16,
  5.796314919267103e-16,
  5.927573133436287e-16,
  5.861569218997485e-16,
  5.847617987997521e-16,
  6.111994065896087e-16,
  5.570263591464215e-16,
  5.916128834847876e-16),
 'F12': (1.8887855180201455e-17,
  2.0233949736154758e-17,
  1.9171417640674825e-17,
  1.9819280067001042e-17,
  2.1312109946976832e-17,
  2.0178984089329455e-17,
  1.8037220896129648e-17,
  1.833256022669569e-17,
  1.8873789906792122e-17,
  1.7892185014983994e-17),
 'F13': (6.769772948022651e-17,
  7.045541353777585e-17,
  7.555958970767534e-17,
  7.495037392647824e-17,
  6.861085330221087e-17,
  7.190122730908434e-17,
  7.16835787869762e-17,
  6.825266854352242e-17,
  7.253984821893087e-17,
  7.262807006166675e-17),
 'F14': (2.6963920212922474e-17,
  2.6836517100004778e-17,
  2.883435602805397e-17,
  2.81953670703756e-17,
  2.6933019184902718e-17,
  2.972665326386079e-17,
  2.5850773291207708e-17,
  2.9112608503347654e-17,
  2.7982168082409583e-17,
  2.5686179738321953e-17),
 'F15': (4.650747757856342e-17,
  4.1973584476553605e-17,
  4.2973578318991375e-17,
  4.159049698633357e-17,
  1.7752086607801916e-14,
  0.0025674131537900048,
  1.3222933439552776e-18,
  2.13415788215718e-17,
  16.99329476455959,
  16.993294764628775),
 'F16': (0.001847150825104225,
  0,
  13.82642560118834,
  7.765333237038272e-16,
  13.826425601137927,
  3.700892602349696e-13,
  0,
  6.772689779726635e-05,
  6.772689710496189e-05,
  6.772689759786975e-05)}

In [58]:
scrap = pd.read_excel("D:\Python\easyml\src\scripts\scrap.xlsx")

In [59]:
scrap.head()

  name company  quantity  price
0   F1       A       744   0.30
1   F1       B       632   0.30
2   F1       C       711   0.29
3   F1       D       535   0.26
4   F1       E       653   0.30

In [72]:
# select the scrap with the name start with F
fremd_scrap = scrap[scrap["name"].str.startswith("F")]
fremd_scrap

    name company  quantity  price
0     F1       A       744   0.30
1     F1       B       632   0.30
2     F1       C       711   0.29
3     F1       D       535   0.26
4     F1       E       653   0.30
..   ...     ...       ...    ...
155  F16       F       644   0.35
156  F16       G       969   0.36
157  F16       H       665   0.35
158  F16       I       659   0.35
159  F16       J       565   0.35

[160 rows x 4 columns]

In [61]:
# substract the x from the fremd_scrap quantity column
fremd_scrap = fremd_scrap.copy()
fremd_scrap.loc[:,"quantity"] = fremd_scrap.loc[:, "quantity"].sub(x)

In [62]:
fremd_scrap["quantity"]

0      744.000000
1      632.000000
2      710.997233
3      137.272402
4      652.999893
          ...
155    644.000000
156    969.000000
157    664.999932
158    658.999932
159    564.999932
Name: quantity, Length: 160, dtype: float64

In [73]:
# check if any quantity is negative
is_negative = any(fremd_scrap["quantity"] < 0)

In [74]:
is_negative

False

In [75]:
fremd_scrap["quantity"].tolist()

[744,
 632,
 711,
 535,
 653,
 952,
 619,
 688,
 884,
 852,
 600,
 602,
 857,
 896,
 682,
 943,
 815,
 568,
 820,
 987,
 722,
 866,
 991,
 893,
 789,
 971,
 887,
 559,
 517,
 595,
 555,
 741,
 689,
 543,
 602,
 805,
 871,
 614,
 916,
 608,
 904,
 755,
 707,
 675,
 516,
 781,
 773,
 539,
 640,
 546,
 830,
 861,
 938,
 900,
 603,
 972,
 957,
 596,
 553,
 759,
 670,
 770,
 535,
 859,
 520,
 659,
 918,
 668,
 908,
 849,
 547,
 978,
 796,
 961,
 739,
 708,
 981,
 753,
 868,
 802,
 905,
 915,
 754,
 983,
 804,
 637,
 797,
 656,
 778,
 943,
 698,
 888,
 692,
 889,
 782,
 564,
 646,
 717,
 649,
 779,
 554,
 773,
 821,
 544,
 535,
 823,
 882,
 679,
 806,
 550,
 824,
 564,
 572,
 975,
 756,
 565,
 798,
 887,
 582,
 888,
 715,
 850,
 850,
 920,
 605,
 746,
 560,
 841,
 801,
 772,
 856,
 677,
 603,
 685,
 513,
 795,
 873,
 546,
 502,
 754,
 681,
 920,
 511,
 645,
 996,
 802,
 952,
 508,
 593,
 828,
 769,
 720,
 609,
 557,
 796,
 644,
 969,
 665,
 659,
 565]